-- ============================================================================
-- ORACLE DBA HACKATHON PROJECT: ONLINE SHOPPING DATABASE
-- Script 02: DDL Schema, Relational Constraints, and Indexing
-- Target Schema: ECOMMERCE_DBA
-- ============================================================================

SET DEFINE OFF;

-- Safely drop existing objects in dependency order
BEGIN
    FOR cur IN (SELECT table_name FROM user_tables WHERE table_name IN ('AUDIT_LOGS', 'ORDER_ITEMS', 'ORDERS', 'PRODUCTS', 'CUSTOMERS', 'CATEGORIES')) LOOP
        EXECUTE IMMEDIATE 'DROP TABLE ' || cur.table_name || ' CASCADE CONSTRAINTS PURGE';
    END LOOP;
END;
/

-- ----------------------------------------------------------------------------
-- 1. CATEGORIES TABLE
-- ----------------------------------------------------------------------------
CREATE TABLE categories (
    category_id         NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_name       VARCHAR2(100) NOT NULL CONSTRAINT uk_category_name UNIQUE,
    description         VARCHAR2(500),
    parent_category_id  NUMBER CONSTRAINT fk_cat_parent REFERENCES categories(category_id) ON DELETE SET NULL,
    is_active           NUMBER(1) DEFAULT 1 NOT NULL CONSTRAINT chk_cat_active CHECK (is_active IN (0, 1)),
    created_at          TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);

COMMENT ON TABLE categories IS 'Stores product classification categories with hierarchical self-referencing capability.';
COMMENT ON COLUMN categories.category_id IS 'Surrogate Primary Key generated via Oracle Identity';
COMMENT ON COLUMN categories.parent_category_id IS 'Self-referencing Foreign Key to model parent subcategory tree';

-- ----------------------------------------------------------------------------
-- 2. CUSTOMERS TABLE
-- ----------------------------------------------------------------------------
CREATE TABLE customers (
    customer_id         NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name          VARCHAR2(60) NOT NULL,
    last_name           VARCHAR2(60) NOT NULL,
    email               VARCHAR2(150) NOT NULL CONSTRAINT uk_cust_email UNIQUE,
    phone               VARCHAR2(25),
    address             VARCHAR2(250) NOT NULL,
    city                VARCHAR2(100) NOT NULL,
    state               VARCHAR2(100) NOT NULL,
    postal_code         VARCHAR2(20) NOT NULL,
    country             VARCHAR2(60) DEFAULT 'USA' NOT NULL,
    status              VARCHAR2(20) DEFAULT 'ACTIVE' NOT NULL CONSTRAINT chk_cust_status CHECK (status IN ('ACTIVE', 'SUSPENDED', 'INACTIVE')),
    created_at          TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);

COMMENT ON TABLE customers IS 'Customer entity storing profiles, contact addresses, and account status.';
COMMENT ON COLUMN customers.email IS 'Unique shopper email address used for identification and notification';

-- ----------------------------------------------------------------------------
-- 3. PRODUCTS TABLE
-- ----------------------------------------------------------------------------
CREATE TABLE products (
    product_id          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_id         NUMBER NOT NULL CONSTRAINT fk_prod_category REFERENCES categories(category_id),
    sku                 VARCHAR2(50) NOT NULL CONSTRAINT uk_prod_sku UNIQUE,
    name                VARCHAR2(160) NOT NULL,
    description         VARCHAR2(1000),
    price               NUMBER(10, 2) NOT NULL CONSTRAINT chk_prod_price CHECK (price >= 0),
    stock_quantity      NUMBER(8) DEFAULT 0 NOT NULL CONSTRAINT chk_prod_stock CHECK (stock_quantity >= 0),
    reorder_level       NUMBER(6) DEFAULT 5 NOT NULL CONSTRAINT chk_prod_reorder CHECK (reorder_level >= 0),
    image_url           VARCHAR2(400),
    is_active           NUMBER(1) DEFAULT 1 NOT NULL CONSTRAINT chk_prod_active CHECK (is_active IN (0, 1)),
    created_at          TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);

COMMENT ON TABLE products IS 'Master product catalog storing SKU, inventory levels, prices, and category.';
COMMENT ON COLUMN products.stock_quantity IS 'Available physical stock, guarded against negative values by check constraint';

-- ----------------------------------------------------------------------------
-- 4. ORDERS TABLE
-- ----------------------------------------------------------------------------
CREATE TABLE orders (
    order_id            NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id         NUMBER NOT NULL CONSTRAINT fk_orders_customer REFERENCES customers(customer_id),
    order_date          TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    total_amount        NUMBER(12, 2) DEFAULT 0.00 NOT NULL CONSTRAINT chk_order_total CHECK (total_amount >= 0),
    status              VARCHAR2(25) DEFAULT 'PENDING' NOT NULL 
                        CONSTRAINT chk_order_status CHECK (status IN ('PENDING', 'PROCESSING', 'SHIPPED', 'DELIVERED', 'CANCELLED')),
    shipping_address    VARCHAR2(350) NOT NULL,
    payment_method      VARCHAR2(30) DEFAULT 'CREDIT_CARD' NOT NULL 
                        CONSTRAINT chk_order_pmethod CHECK (payment_method IN ('CREDIT_CARD', 'DEBIT_CARD', 'PAYPAL', 'NET_BANKING', 'COD')),
    payment_status      VARCHAR2(20) DEFAULT 'PENDING' NOT NULL 
                        CONSTRAINT chk_order_pstatus CHECK (payment_status IN ('PENDING', 'PAID', 'FAILED', 'REFUNDED')),
    created_at          TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);

COMMENT ON TABLE orders IS 'Customer orders ledger tracking status lifecycle and transaction amount.';

-- ----------------------------------------------------------------------------
-- 5. ORDER_ITEMS TABLE
-- ----------------------------------------------------------------------------
CREATE TABLE order_items (
    order_item_id       NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id            NUMBER NOT NULL CONSTRAINT fk_item_order REFERENCES orders(order_id) ON DELETE CASCADE,
    product_id          NUMBER NOT NULL CONSTRAINT fk_item_product REFERENCES products(product_id),
    quantity            NUMBER(6) NOT NULL CONSTRAINT chk_item_qty CHECK (quantity > 0),
    unit_price          NUMBER(10, 2) NOT NULL CONSTRAINT chk_item_price CHECK (unit_price >= 0),
    subtotal            NUMBER(12, 2) NOT NULL CONSTRAINT chk_item_subtotal CHECK (subtotal >= 0)
);

COMMENT ON TABLE order_items IS 'Line items composing each order, tracking quantity and historical unit price.';

-- ----------------------------------------------------------------------------
-- 6. AUDIT_LOGS TABLE
-- ----------------------------------------------------------------------------
CREATE TABLE audit_logs (
    log_id              NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    table_name          VARCHAR2(40) NOT NULL,
    record_id           NUMBER NOT NULL,
    action              VARCHAR2(20) NOT NULL,
    old_values          VARCHAR2(1000),
    new_values          VARCHAR2(1000),
    performed_by        VARCHAR2(60) DEFAULT USER NOT NULL,
    logged_at           TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);

COMMENT ON TABLE audit_logs IS 'DBA audit ledger logging critical modifications to sensitive inventory and order records.';

-- ----------------------------------------------------------------------------
-- 7. ORACLE DBA INDEXES
-- ----------------------------------------------------------------------------
CREATE INDEX idx_products_category ON products(category_id);
CREATE INDEX idx_orders_customer_date ON orders(customer_id, order_date DESC);
CREATE INDEX idx_orders_status ON orders(status);
CREATE INDEX idx_order_items_order ON order_items(order_id);
CREATE INDEX idx_order_items_product ON order_items(product_id);

COMMIT;
